# Generated by Django 5.2.5 on 2025-11-23 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Progresso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etapa", models.CharField(max_length=255)),
                ("concluida", models.BooleanField(default=False)),
                ("data_conclusao", models.DateTimeField(blank=True, null=True)),
                (
                    "trilha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresso",
                        to="api.trilha",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso",
                "verbose_name_plural": "Progresso",
                "ordering": ["id"],
            },
        ),
    ]
