# Generated by Django 5.2.5 on 2025-11-24 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_progresso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrilhaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('solicitacao_original', models.TextField(help_text='Texto original enviado pelo usuário')),
                ('conteudo_json', models.JSONField(help_text='Conteúdo completo da trilha em formato JSON')),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas_curso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trilha de Curso (IA)',
                'verbose_name_plural': 'Trilhas de Curso (IA)',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
