# Generated by Django 5.2.5 on 2025-11-24 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trilhacurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilhacurso',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trilhas_curso', to='api.area'),
        ),
        migrations.AlterField(
            model_name='trilhacurso',
            name='solicitacao_original',
            field=models.TextField(blank=True, help_text='Texto original enviado pelo usuário (vazio para criação manual)'),
        ),
    ]
