# Generated by Django 5.2.5 on 2025-09-22 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrilhaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da trilha de curso', max_length=255)),
                ('descricao', models.TextField(help_text='Descrição detalhada da trilha')),
                ('solicitacao_original', models.TextField(help_text='Solicitação original do usuário')),
                ('conteudo_json', models.JSONField(help_text='Conteúdo estruturado da trilha em JSON')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativa', models.BooleanField(default=True, help_text='Indica se a trilha está ativa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas_curso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trilha de Curso',
                'verbose_name_plural': 'Trilhas de Curso',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
